/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(complex_to_interleaved_float_vcf.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(4e8a32adbbf1138755f5ecb972f864f8)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <dab/complex_to_interleaved_float_vcf.h>
// pydoc.h is automatically generated in the build directory
#include <complex_to_interleaved_float_vcf_pydoc.h>

void bind_complex_to_interleaved_float_vcf(py::module& m)
{

    using complex_to_interleaved_float_vcf    = ::gr::dab::complex_to_interleaved_float_vcf;


    py::class_<complex_to_interleaved_float_vcf, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<complex_to_interleaved_float_vcf>>(m, "complex_to_interleaved_float_vcf", D(complex_to_interleaved_float_vcf))

        .def(py::init(&complex_to_interleaved_float_vcf::make),
           py::arg("length"),
           D(complex_to_interleaved_float_vcf,make)
        )
        



        ;




}








