/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(control_stream_to_tag_cc.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(690315bf92b553381028c368a095e47c)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <dab/control_stream_to_tag_cc.h>
// pydoc.h is automatically generated in the build directory
#include <control_stream_to_tag_cc_pydoc.h>

void bind_control_stream_to_tag_cc(py::module& m)
{

    using control_stream_to_tag_cc    = ::gr::dab::control_stream_to_tag_cc;


    py::class_<control_stream_to_tag_cc, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<control_stream_to_tag_cc>>(m, "control_stream_to_tag_cc", D(control_stream_to_tag_cc))

        .def(py::init(&control_stream_to_tag_cc::make),
           py::arg("tag_str"),
           py::arg("vlen") = 1,
           D(control_stream_to_tag_cc,make)
        )
        



        ;




}








