/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(diff_phasor_vcc.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(be6f06d74bb4a7d733b23e45be0c5d9a)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <dab/diff_phasor_vcc.h>
// pydoc.h is automatically generated in the build directory
#include <diff_phasor_vcc_pydoc.h>

void bind_diff_phasor_vcc(py::module& m)
{

    using diff_phasor_vcc    = ::gr::dab::diff_phasor_vcc;


    py::class_<diff_phasor_vcc, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<diff_phasor_vcc>>(m, "diff_phasor_vcc", D(diff_phasor_vcc))

        .def(py::init(&diff_phasor_vcc::make),
           py::arg("length"),
           D(diff_phasor_vcc,make)
        )
        



        ;




}








