/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(estimate_sample_rate_bf.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(a3157d80fe17573100d3608eff947730)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <dab/estimate_sample_rate_bf.h>
// pydoc.h is automatically generated in the build directory
#include <estimate_sample_rate_bf_pydoc.h>

void bind_estimate_sample_rate_bf(py::module& m)
{

    using estimate_sample_rate_bf    = ::gr::dab::estimate_sample_rate_bf;


    py::class_<estimate_sample_rate_bf, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<estimate_sample_rate_bf>>(m, "estimate_sample_rate_bf", D(estimate_sample_rate_bf))

        .def(py::init(&estimate_sample_rate_bf::make),
           py::arg("expected_sample_rate"),
           py::arg("frame_length"),
           D(estimate_sample_rate_bf,make)
        )
        



        ;




}








