/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(firecode_check_bb.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(79874a829c738577cc8b65cd5dd33e27)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <dab/firecode_check_bb.h>
// pydoc.h is automatically generated in the build directory
#include <firecode_check_bb_pydoc.h>

void bind_firecode_check_bb(py::module& m)
{

    using firecode_check_bb    = ::gr::dab::firecode_check_bb;


    py::class_<firecode_check_bb, gr::block, gr::basic_block,
        std::shared_ptr<firecode_check_bb>>(m, "firecode_check_bb", D(firecode_check_bb))

        .def(py::init(&firecode_check_bb::make),
           py::arg("bit_rate_n"),
           D(firecode_check_bb,make)
        )
        




        
        .def("get_firecode_passed",&firecode_check_bb::get_firecode_passed,       
            D(firecode_check_bb,get_firecode_passed)
        )

        ;




}








