/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(insert_null_symbol.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(d6fdd82c74fb25ef86c65a83552f930a)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <dab/insert_null_symbol.h>
// pydoc.h is automatically generated in the build directory
#include <insert_null_symbol_pydoc.h>

void bind_insert_null_symbol(py::module& m)
{

    using insert_null_symbol    = ::gr::dab::insert_null_symbol;


    py::class_<insert_null_symbol, gr::block, gr::basic_block,
        std::shared_ptr<insert_null_symbol>>(m, "insert_null_symbol", D(insert_null_symbol))

        .def(py::init(&insert_null_symbol::make),
           py::arg("ns_length"),
           py::arg("symbol_length"),
           D(insert_null_symbol,make)
        )
        



        ;




}








