/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(mp2_decode_bs.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(44c9a935a16a60f386b36e7d47291637)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <dab/mp2_decode_bs.h>
// pydoc.h is automatically generated in the build directory
#include <mp2_decode_bs_pydoc.h>

void bind_mp2_decode_bs(py::module& m)
{

    using mp2_decode_bs    = ::gr::dab::mp2_decode_bs;


    py::class_<mp2_decode_bs, gr::block, gr::basic_block,
        std::shared_ptr<mp2_decode_bs>>(m, "mp2_decode_bs", D(mp2_decode_bs))

        .def(py::init(&mp2_decode_bs::make),
           py::arg("bit_rate_n"),
           D(mp2_decode_bs,make)
        )
        




        
        .def("get_sample_rate",&mp2_decode_bs::get_sample_rate,       
            D(mp2_decode_bs,get_sample_rate)
        )

        ;




}








