/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(ofdm_remove_first_symbol_vcc.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(6c84c73f49632da7872a3842bab42354)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <dab/ofdm_remove_first_symbol_vcc.h>
// pydoc.h is automatically generated in the build directory
#include <ofdm_remove_first_symbol_vcc_pydoc.h>

void bind_ofdm_remove_first_symbol_vcc(py::module& m)
{

    using ofdm_remove_first_symbol_vcc    = ::gr::dab::ofdm_remove_first_symbol_vcc;


    py::class_<ofdm_remove_first_symbol_vcc, gr::block, gr::basic_block,
        std::shared_ptr<ofdm_remove_first_symbol_vcc>>(m, "ofdm_remove_first_symbol_vcc", D(ofdm_remove_first_symbol_vcc))

        .def(py::init(&ofdm_remove_first_symbol_vcc::make),
           py::arg("vlen"),
           D(ofdm_remove_first_symbol_vcc,make)
        )
        



        ;




}








