/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(ofdm_coarse_frequency_correct.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(d3f819ab3acf990739e055cd5d617489)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <dab/ofdm_coarse_frequency_correct.h>
// pydoc.h is automatically generated in the build directory
#include <ofdm_coarse_frequency_correct_pydoc.h>

void bind_ofdm_coarse_frequency_correct(py::module& m)
{

    using ofdm_coarse_frequency_correct    = ::gr::dab::ofdm_coarse_frequency_correct;


    py::class_<ofdm_coarse_frequency_correct, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<ofdm_coarse_frequency_correct>>(m, "ofdm_coarse_frequency_correct", D(ofdm_coarse_frequency_correct))

        .def(py::init(&ofdm_coarse_frequency_correct::make),
           py::arg("fft_length"),
           py::arg("num_carriers"),
           py::arg("cp_length"),
           D(ofdm_coarse_frequency_correct,make)
        )
        



        ;




}








