/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(prune.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(ca5cc4dac41744dd0eaa25d704dcecb0)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <dab/prune.h>
// pydoc.h is automatically generated in the build directory
#include <prune_pydoc.h>

void bind_prune(py::module& m)
{

    using prune    = ::gr::dab::prune;


    py::class_<prune, gr::block, gr::basic_block,
        std::shared_ptr<prune>>(m, "prune", D(prune))

        .def(py::init(&prune::make),
           py::arg("itemsize"),
           py::arg("length"),
           py::arg("prune_start"),
           py::arg("prune_end"),
           D(prune,make)
        )
        



        ;




}








