/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(qpsk_demapper_vcb.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(896d6427efb415cbcdeea3bdab32ffb6)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <dab/qpsk_demapper_vcb.h>
// pydoc.h is automatically generated in the build directory
#include <qpsk_demapper_vcb_pydoc.h>

void bind_qpsk_demapper_vcb(py::module& m)
{

    using qpsk_demapper_vcb    = ::gr::dab::qpsk_demapper_vcb;


    py::class_<qpsk_demapper_vcb, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<qpsk_demapper_vcb>>(m, "qpsk_demapper_vcb", D(qpsk_demapper_vcb))

        .def(py::init(&qpsk_demapper_vcb::make),
           py::arg("symbol_length"),
           D(qpsk_demapper_vcb,make)
        )
        



        ;




}








