/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(repartition_vectors.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(8bf98a5d036d7a5735276efde863dc2c)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <dab/repartition_vectors.h>
// pydoc.h is automatically generated in the build directory
#include <repartition_vectors_pydoc.h>

void bind_repartition_vectors(py::module& m)
{

    using repartition_vectors    = ::gr::dab::repartition_vectors;


    py::class_<repartition_vectors, gr::block, gr::basic_block,
        std::shared_ptr<repartition_vectors>>(m, "repartition_vectors", D(repartition_vectors))

        .def(py::init(&repartition_vectors::make),
           py::arg("itemsize"),
           py::arg("vlen_in"),
           py::arg("vlen_out"),
           py::arg("multiply"),
           py::arg("divide"),
           D(repartition_vectors,make)
        )
        



        ;




}








