/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(select_subch_vfvf.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(8f2c9693643cbbae5069c93233ea28a0)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <dab/select_subch_vfvf.h>
// pydoc.h is automatically generated in the build directory
#include <select_subch_vfvf_pydoc.h>

void bind_select_subch_vfvf(py::module& m)
{

    using select_subch_vfvf    = ::gr::dab::select_subch_vfvf;


    py::class_<select_subch_vfvf, gr::block, gr::basic_block,
        std::shared_ptr<select_subch_vfvf>>(m, "select_subch_vfvf", D(select_subch_vfvf))

        .def(py::init(&select_subch_vfvf::make),
           py::arg("vlen_in"),
           py::arg("vlen_out"),
           py::arg("address"),
           py::arg("total_size"),
           D(select_subch_vfvf,make)
        )
        



        ;




}








