/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(valve_ff.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(e6be4311c5039f6b6b8864de424611b2)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <dab/valve_ff.h>
// pydoc.h is automatically generated in the build directory
#include <valve_ff_pydoc.h>

void bind_valve_ff(py::module& m)
{

    using valve_ff    = ::gr::dab::valve_ff;


    py::class_<valve_ff, gr::block, gr::basic_block,
        std::shared_ptr<valve_ff>>(m, "valve_ff", D(valve_ff))

        .def(py::init(&valve_ff::make),
           py::arg("closed"),
           py::arg("feed_with_zeros") = false,
           D(valve_ff,make)
        )
        




        
        .def("set_closed",&valve_ff::set_closed,       
            py::arg("closed"),
            D(valve_ff,set_closed)
        )


        
        .def("set_feed_with_zeros",&valve_ff::set_feed_with_zeros,       
            py::arg("feed_with_zeros"),
            D(valve_ff,set_feed_with_zeros)
        )

        ;




}








