#!/usr/bin/env python

import argparse
import sys

import grdab.app

parser = argparse.ArgumentParser(description='DAB radio (grdab)')
subparsers = parser.add_subparsers()

parser_receive = subparsers.add_parser('receive', help='Receive DAB+ audio')
parser_receive.add_argument("-f","--freq", help="Frequency in MHz", type=float, default=220.352)

parser_info = subparsers.add_parser('info', help='Get channel details')
parser_info.add_argument("-f","--freq", help="Frequency in MHz", type=float, default=220.352)

parser_adjust = subparsers.add_parser('adjust', help='Find optimum gain and freq error ppm settings')
parser_adjust.add_argument("-f","--freq", help="Frequency in MHz", type=float, default=220.352)

import grdab.app.config
import os
cfg_dir = "".join([os.getenv("HOME"),"/.grdab"])
cfg = grdab.app.config.Configuration(cfg_dir)

rf_gain = 50
if_gain = 0
bb_gain = 0
ppm = 0

if "gain" in cfg.adjust_config:
  rf_gain = cfg.adjust_config["gain"]["gain_rf"]
  if_gain = cfg.adjust_config["gain"]["gain_if"]
  bb_gain = cfg.adjust_config["gain"]["gain_bb"]

if "ppm" in cfg.adjust_config:
  ppm     = cfg.adjust_config["ppm"]

def receive_handler(res):
  print("receive handler")
  grdab.app.receive_dabplus(frequency=(res.freq*1e6), rf_gain=rf_gain, if_gain=if_gain, bb_gain=bb_gain, ppm=ppm)

def info_handler(res):
  print("info handler")
  grdab.app.get_channels(frequency=(res.freq*1e6))

def adjust_handler(res):
  import grdab.app.tune_gain_and_ppm
  print("will open GUI to adjust gain and ppm")
  grdab.app.tune_gain_and_ppm.main(rf_gain=rf_gain, if_gain=if_gain, bb_gain=bb_gain, ppm=ppm)

parser_receive.set_defaults(func=receive_handler)
parser_info.set_defaults(func=info_handler)
parser_adjust.set_defaults(func=adjust_handler)
args = parser.parse_args()

args.func(args)

